name: mace_0.3.8
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - chgnet=0.3.8=py310hc51659f_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - debugpy=1.8.7=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - git-lfs=3.7.0=h59e48b9_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.28.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - nvidia-ml=7.352.0=py_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.5.1=h7b32b05_0
  - opt_einsum_fx=0.1.4=pyhd8ed1ab_1
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py310ha75aee5_2
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=26.2.0=py310h71f11fc_3
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torch-ema=0.3=pyhd8ed1ab_1
  - torchmetrics=1.7.4=pyhd8ed1ab_0
  - tornado=6.4.1=py310ha75aee5_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - urllib3=2.2.2=py310h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h3b0a872_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.2.2
      - aioitertools==0.12.0
      - annotated-types==0.7.0
      - ase==3.25.0
      - attrs==25.1.0
      - bcrypt==4.3.0
      - bibtexparser==1.4.3
      - boto3==1.40.15
      - botocore==1.40.15
      - cffi==1.17.1
      - click==8.1.7
      - configargparse==1.7
      - contourpy==1.3.2
      - cryptography==45.0.6
      - cuequivariance==0.5.1
      - cuequivariance-ops-cu12==0.5.1
      - cuequivariance-ops-torch-cu12==0.5.1
      - cuequivariance-torch==0.5.1
      - cycler==0.12.1
      - cython==3.1.2
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - e3nn==0.4.4
      - emmet-core==0.84.10rc2
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.1
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gh==0.0.4
      - git-filter-repo==2.47.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.71.0
      - h5py==3.12.1
      - invoke==2.2.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - latexcodec==3.0.1
      - lightning-utilities==0.11.8
      - llvmlite==0.44.0
      - lmdb==1.7.2
      - mace-torch==0.3.14
      - maggma==0.72.0
      - markdown==3.8
      - matplotlib==3.9.2
      - matscipy==1.1.1
      - mongomock==4.3.0
      - monty==2025.3.3
      - mp-api==0.45.8
      - msgpack==1.1.1
      - narwhals==1.28.0
      - nbformat==5.10.4
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - orjson==3.11.0
      - palettable==3.3.3
      - pandas==2.2.3
      - paramiko==4.0.0
      - plotly==6.0.0
      - prettytable==3.12.0
      - protobuf==5.29.4
      - pybtex==0.25.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydash==8.0.5
      - pymatgen==2025.6.14
      - pymatgen-io-validation==0.1.1
      - pymongo==4.10.1
      - pynacl==1.5.0
      - pynndescent==0.5.13
      - pynvml==12.0.0
      - pyparsing==3.2.0
      - python-dotenv==1.1.1
      - python-hostlist==2.0.0
      - pytz==2024.2
      - referencing==0.36.2
      - rpds-py==0.23.1
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.13.1
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - sentinels==1.1.1
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - smart-open==7.3.0.post1
      - smmap==5.0.1
      - spglib==2.6.0
      - sshtunnel==0.4.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-inspection==0.4.1
      - tzdata==2024.2
      - umap-learn==0.5.7
      - uncertainties==3.2.3
      - wandb==0.18.7
      - werkzeug==3.1.3
      - wrapt==1.17.3
prefix: /home/phanim/harshitrawat/miniconda3/envs/mace_0.3.8
